### ISSUE TITLE
Can't unmarshal when using start and end in ListUptimeTestHistory function

### ISSUE THREAD

**Issue by handikacatur** [StatusCakeDev/statuscake-go#1]
Hello guys, I tried to fetch uptime history using start and end method but it gives me error json unmarshal. Here's my code:
```go
fmt.Println(s.Unix(), e.Unix())
	res, err := client.ListUptimeTestHistory(context.Background(), "6128010").
		Start(1632268800).End(1632355140).Limit(100).
		Execute()

	if err != nil {
		panic(err)
	}

	data, _ := json.MarshalIndent(res.Data, "", "🐱")

	fmt.Print(string(data))
```

And here is the error:
```bash
panic: json: cannot unmarshal array into Go struct field UptimeTestHistory.data of type map[string]statuscake.UptimeTestHistoryResult: failed to deserialise response body
```

I don't know if it's not the way I should use the method or it's bug on the code itself. I don't find any example with Start and End method both in documentation and github. I'm using Go 1.17 on darwin.

**Comment by tomasbasham** [comment]
Hi @handikacatur. We've experienced a problem with the StatusCake API itself that had been removing the timestamp keys from the returned JSON. This is what was causing the marshal error. We since applied a fix for this issue which shall be deployed shortly. Thank you for bringing it to our attention.

**Comment by tomasbasham** [comment]
@handikacatur This has now been deployed and should now be working. We used the code you supplied above to make sure a valid response was returned.
