### ISSUE TITLE
Cannot update BasicUser & BasicPass values

### ISSUE THREAD

**Issue by G-Rath** [StatusCakeDev/statuscake-go#2]
I suspect this is an API issue rather than within the client, but figured this would be the best place to report it for now.

I've been working on writing a custom Terraform provider for StatusCake using this client & the beta api, and it seems that the `BasicUser` & `BasicPass` properties for an uptime request cannot be update by the api client:

```golang
package main

import (
	"context"
	"github.com/StatusCakeDev/statuscake-go"
	"log"
	"os"
)

func main() {
	apiToken, _ := os.LookupEnv("STATUSCAKE_API_KEY")

	client := statuscake.NewAPIClient(apiToken)

	res, err := client.CreateUptimeTest(context.TODO()).
		Name("my test").
		TestType("HTTP").
		WebsiteURL("https://www.example.com").
		CheckRate(300).
		Execute()

	if err != nil {
		panic(err)
	}

	log.Println("Successfully created Uptime test")

	err = client.UpdateUptimeTest(context.TODO(), res.Data.NewID).
		BasicUser("user").
		BasicPass("pass").
		Execute()

	if err != nil {
		panic(err)
	}

	log.Println("Successfully updated Uptime test")
}

```

```
terraform-provider-statuscake2 on  main took 3s
❯ go run te.go
2021/10/03 16:22:55 Successfully created Uptime test
panic: Invalid request. No changes were requested. Please check your inputs and try again.

goroutine 1 [running]:
main.main()
        /c/Users/G-Rath/workspace/projects-personal/terraform-provider-statuscake2/te.go:34 +0x6f7
exit status 2
```

**Comment by tomasbasham** [comment]
Hi, we'll take a look into this. Thanks for reporting it. You may also be interested to know that we are currently developing an official Terraform provider using this client code. If you are keen to take a look the code can be found [here](https://github.com/StatusCakeDev/terraform-provider-statuscake/tree/v2)

**Comment by G-Rath** [comment]
Thanks - I am definitely interested in an official provider; I've already published our [unofficial provider](https://github.com/ackama/terraform-provider-statuscake) and was planning on adding some more resources to it.

Do you have any sense of when you think your new provider might be ready?

**Comment by tomasbasham** [comment]
Sorry for the delay. This has now been fixed. We hope to also get a beta version of a new Terraform provider released this week.
